version: 2

jobs:
  image-tests-mpl153:
    docker:
      - image: astropy/image-tests-py35-mpl153:1.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install reproject astropy==2.0.7 scikit-image==0.12.3
      - run:
          name: Run tests
          command: pytest aplpy --remote-data=any --mpl
  image-tests-mpl202:
    docker:
      - image: astropy/image-tests-py35-mpl202:1.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install reproject astropy==3.0.3 scikit-image==0.14.0
      - run:
          name: Run tests
          command: pytest aplpy --remote-data=any --mpl
  image-tests-mpl212:
    docker:
      - image: astropy/image-tests-py35-mpl212:1.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install reproject astropy==3.0.3 scikit-image==0.14.0
      - run:
          name: Run tests
          command: pytest aplpy --remote-data=any --mpl
  image-tests-mpl222:
    docker:
      - image: astropy/image-tests-py35-mpl222:1.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install reproject astropy==3.0.3 scikit-image==0.14.0
      - run:
          name: Run tests
          command: pytest aplpy --remote-data=any --mpl


workflows:
  version: 2
  build_and_test:
    jobs:
      - image-tests-mpl153
      - image-tests-mpl202
      - image-tests-mpl212
      - image-tests-mpl222
